# Generated by Django 3.2.3 on 2021-08-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de registro')),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Gastos',
                'verbose_name_plural': 'Gastos',
                'db_table': 'gastos',
                'ordering': ['id'],
            },
        ),
    ]
