# Generated by Django 3.2.3 on 2021-08-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'ordering': ['id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
    ]
