# Generated by Django 3.2.5 on 2021-08-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gastos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gastos',
            table='gastos',
        ),
    ]
