# Generated by Django 3.2.5 on 2021-08-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_alter_gastos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de registro'),
        ),
    ]
