# Generated by Django 3.2.5 on 2021-08-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_alter_gastos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='amount',
            field=models.FloatField(max_length=15, verbose_name='Monto'),
        ),
    ]
