# Generated by Django 3.2.5 on 2021-08-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_alter_gastos_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='amount',
            field=models.IntegerField(verbose_name='Monto'),
        ),
    ]
