# Generated by Django 3.2.6 on 2021-08-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('gastos', '0012_alter_gastos_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
