# Generated by Django 3.2.3 on 2021-09-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_gastos_options'),
        ('gastos', '0013_auto_20210817_1349'),
    ]

    operations = [
    ]
