# Generated by Django 3.2.6 on 2021-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0014_merge_20210908_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='semana',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='semana'),
        ),
    ]
