# Generated by Django 3.2.6 on 2021-09-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('gastos', '0015_gastos_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='semana',
        ),
        migrations.CreateModel(
            name='semanas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.FloatField(blank=True, default=None, null=True, verbose_name='semana')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
    ]
