# Generated by Django 3.2.6 on 2021-09-15 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0016_auto_20210915_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semanas',
            name='category',
        ),
        migrations.AddField(
            model_name='semanas',
            name='gastos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.gastos'),
        ),
    ]
