# Generated by Django 3.2.6 on 2021-09-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0017_auto_20210915_1618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='semanas',
        ),
    ]
