# Generated by Django 3.2.6 on 2021-09-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0018_delete_semanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gastos',
            name='user_creation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.registrousuario'),
            preserve_default=False,
        ),
    ]
