# Generated by Django 3.2.6 on 2021-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0020_alter_gastos_user_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='week',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Week'),
        ),
    ]
