# Generated by Django 3.2.5 on 2021-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_alter_presupuesto_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Monto'),
        ),
    ]
