# Generated by Django 3.2.6 on 2021-08-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('presupuesto', '0004_alter_presupuesto_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
