# Generated by Django 3.2.6 on 2021-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_alter_presupuesto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Monto'),
        ),
    ]
