# Generated by Django 3.2.6 on 2021-09-21 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_c_m', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de inicio')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'meta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AmountMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metas.metas')),
            ],
            options={
                'verbose_name': 'AmountMeta',
                'verbose_name_plural': 'AmountMetas',
                'db_table': 'AmountMeta',
                'ordering': ['id'],
            },
        ),
    ]
