# Generated by Django 3.2.5 on 2021-08-10 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_c_m', models.DateField(verbose_name='Fecha de registro')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'meta',
                'ordering': ['id'],
            },
        ),
    ]
