# Generated by Django 3.2.5 on 2021-08-10 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metas',
            old_name='valor',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='metas',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='metas',
            name='f_c_m',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
    ]
