# Generated by Django 3.2.5 on 2021-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_auto_20210809_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Monto'),
        ),
    ]
