# Generated by Django 3.2.6 on 2021-09-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_auto_20210817_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Porcentaje'),
        ),
    ]
