# Generated by Django 3.2.6 on 2021-09-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0006_auto_20210916_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='porcentaje',
        ),
    ]
