# Generated by Django 3.2.6 on 2021-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0007_remove_metas_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='amount_meta',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Monto de meta'),
        ),
    ]
