# Generated by Django 3.2.6 on 2021-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0008_metas_amount_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountMetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'AmountMeta',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='metas',
            name='amount_meta',
        ),
    ]
