# Generated by Django 3.2.3 on 2021-09-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informes',
            options={'ordering': ['id'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AddField(
            model_name='informes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.AddField(
            model_name='informes',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='informes',
            name='gastos',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Gasto'),
        ),
        migrations.AddField(
            model_name='informes',
            name='presupuesto',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='presupuesto'),
        ),
        migrations.AddField(
            model_name='informes',
            name='semana',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='semana'),
        ),
        migrations.AlterModelTable(
            name='informes',
            table='informe',
        ),
    ]
