# Generated by Django 3.2.3 on 2021-09-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_auto_20210906_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='restante',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='restante'),
        ),
    ]
