# Generated by Django 3.2.3 on 2021-09-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_informes_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informes',
            name='restante',
        ),
    ]
