# Generated by Django 3.2.6 on 2021-09-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_alter_presupuesto_amount'),
        ('informes', '0005_auto_20210915_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='presupuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto'),
        ),
    ]
