# Generated by Django 3.2.6 on 2021-09-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_alter_presupuesto_amount'),
        ('gastos', '0014_merge_20210908_1119'),
        ('informes', '0006_informes_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='gastos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gastos.gastos'),
        ),
        migrations.AddField(
            model_name='informes',
            name='presupuesto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='gastos',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Gasto'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='presupuesto',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='presupuesto'),
        ),
    ]
