# Generated by Django 3.2.6 on 2021-09-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0009_informes_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informes',
            options={'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
    ]
