# Generated by Django 3.2.6 on 2021-09-25 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='user_creation',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to='registro.registrousuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Categoria'),
        ),
    ]
