# Generated by Django 3.2.6 on 2021-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20210925_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='category',
            field=models.CharField(default=4, max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
