# Generated by Django 3.2.6 on 2021-09-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0003_alter_categoria_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='user_creation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
