# Generated by Django 3.2.6 on 2021-09-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20210902_1725'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuario',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfilmodel'),
        ),
    ]
