# Generated by Django 3.2.6 on 2021-08-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%y/%m/%d'),
        ),
    ]
