# Generated by Django 3.2.6 on 2021-09-07 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registrousuario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrousuario',
            name='image',
        ),
    ]
