# Generated by Django 3.2.6 on 2021-09-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_registrousuario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/%Y/%m/%d'),
        ),
    ]
