# Generated by Django 3.2.6 on 2021-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_registrousuario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrousuario',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
