# Generated by Django 3.2.5 on 2021-07-02 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=20, verbose_name='Apellido')),
                ('date_joined', models.DateField(default=datetime.datetime(2021, 7, 2, 18, 59, 50, 599246), verbose_name='Fecha de registro')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%y/%m/d')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
    ]
