# Generated by Django 3.2.5 on 2021-08-03 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'ordering': ['id'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='metas',
            options={'ordering': ['id'], 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'ordering': ['id'], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 16, 1, 24, 367050), verbose_name='Fecha de registro'),
        ),
        migrations.AlterModelTable(
            name='gastos',
            table='gasto',
        ),
        migrations.AlterModelTable(
            name='metas',
            table='meta',
        ),
        migrations.AlterModelTable(
            name='presupuesto',
            table='presupuesto',
        ),
    ]
