# Generated by Django 3.2.5 on 2021-08-04 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210803_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas',
            name='date',
        ),
        migrations.AddField(
            model_name='metas',
            name='date_join',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 19, 52, 25, 293388), verbose_name='Fecha de registro'),
        ),
    ]
