# Generated by Django 3.2.5 on 2021-08-04 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210803_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metas',
            old_name='date_join',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 8, 3, 19, 52, 51, 557792), verbose_name='Fecha de registro'),
        ),
    ]
