# Generated by Django 3.2.5 on 2021-08-10 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210803_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gastos',
        ),
        migrations.DeleteModel(
            name='metas',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
    ]
