# Generated by Django 3.2.6 on 2021-08-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210809_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
