# Generated by Django 3.2.6 on 2021-09-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
