# Generated by Django 3.2.6 on 2021-08-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Perfil',
        ),
    ]
