# Generated by Django 3.2.6 on 2021-09-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20210902_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmodel',
            name='image',
        ),
    ]
