# Generated by Django 3.2.6 on 2021-09-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20210906_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='image',
        ),
    ]
