# Generated by Django 3.2.6 on 2021-09-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_remove_perfil_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='PerfilModel',
        ),
    ]
