# Generated by Django 3.2.6 on 2021-09-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_rename_perfil_perfilmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/%Y/%m/%d'),
        ),
    ]
