# Generated by Django 3.2.6 on 2021-09-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_perfilmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmodel',
            name='image',
        ),
    ]
